name: test_flutter

description: "A new Flutter project to test it."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.2
  intl: ^0.19.0 # Ensure this matches the version required by flutter_localizations
  flutter_localizations:
    sdk: flutter # Include flutter_localizations for localization support
  provider: ^6.0.3 # Add this for state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.0.0 # Add this for localization generation

flutter:
  uses-material-design: true
  generate: true # Ensure this line is included to enable code generation for localization

  assets:
    - assets/flags/usa.png
    - assets/flags/greece.png
    # Add more flags or other assets as needed

